version: "3.8"

services:
  app3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app3
    expose:
      - 80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
